# Generated by Django 3.2.4 on 2021-06-23 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveIntegerField(verbose_name='Значение ответа')),
                ('date_time_answer', models.DateTimeField(verbose_name='Дата и время ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_with_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionwithoption', verbose_name='Вопросы с вариантами ответов')),
                ('question_with_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionwithscale', verbose_name='Вопросы со шкалой')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователя',
            },
        ),
        migrations.CreateModel(
            name='Datings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(blank=True, choices=[('A1', 'Алгоритм 1'), ('A2', 'Алгоритм 2'), ('A3', 'Алгоритм 3'), ('HBF', 'История по ощущениям')], max_length=120, null=True, verbose_name='Алгоритм')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datingsfirstuser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 1')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datingsseconduser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 2')),
            ],
            options={
                'verbose_name': 'Совпадения пользователя',
                'verbose_name_plural': 'Совпадения пользователей',
            },
        ),
        migrations.CreateModel(
            name='AnswersCounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_count1', models.PositiveIntegerField(verbose_name="Количество ответов '1'")),
                ('answers_count2', models.PositiveIntegerField(verbose_name="Количество ответов '2'")),
                ('answers_count3', models.PositiveIntegerField(verbose_name="Количество ответов '3'")),
                ('answers_count4', models.PositiveIntegerField(verbose_name="Количество ответов '4'")),
                ('answers_count5', models.PositiveIntegerField(verbose_name="Количество ответов '5'")),
                ('date_time_counting', models.DateTimeField(verbose_name='Дата и время подсчёта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подсчет ответов',
                'verbose_name_plural': 'Подсчеты ответов',
            },
        ),
    ]
