# Generated by Django 3.2.5 on 2021-07-09 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_remove_answeroption_answer_value'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOptionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.answeroption', verbose_name='Значение ответа')),
                ('question_with_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionwithoption', verbose_name='Вопросы с вариантами ответов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя на вопрос с вариантами',
                'verbose_name_plural': 'Ответы пользователя на вопрос с вариантами',
            },
        ),
        migrations.CreateModel(
            name='UserScaleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveIntegerField(verbose_name='Значение ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_scale_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.answerscale', verbose_name='Строка вопроса со шкалой')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя на вопрос со шкалой',
                'verbose_name_plural': 'Ответы пользователя на вопрос со шкалой',
            },
        ),
        migrations.RemoveField(
            model_name='answerscounting',
            name='date_time_counting',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
