# Generated by Django 3.2.4 on 2021-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerscounting',
            name='date_time_counting',
            field=models.DateTimeField(verbose_name='Дата и время подсчёта'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='date_time_answer',
            field=models.DateTimeField(verbose_name='Дата и время ответа'),
        ),
    ]
