# Generated by Django 3.2.5 on 2021-07-09 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210623_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOptionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveIntegerField(verbose_name='Значение ответа')),
                ('date_time_answer', models.DateTimeField(verbose_name='Дата и время ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_with_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionwithoption', verbose_name='Вопросы с вариантами ответов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя на вопрос с вариантами',
                'verbose_name_plural': 'Ответы пользователя на вопрос с вариантами',
            },
        ),
        migrations.CreateModel(
            name='UserScaleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveIntegerField(verbose_name='Значение ответа')),
                ('date_time_answer', models.DateTimeField(verbose_name='Дата и время ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_with_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionwithscale', verbose_name='Вопросы со шкалой')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя на вопрос со шкалой',
                'verbose_name_plural': 'Ответы пользователя на вопрос со шкалой',
            },
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
