# Generated by Django 3.2.5 on 2021-07-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_datings_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerscounting',
            options={'verbose_name': 'Подсчет ответов', 'verbose_name_plural': 'Подсчеты ответов пользователей'},
        ),
        migrations.AlterModelOptions(
            name='useroptionanswer',
            options={'verbose_name': 'Ответ пользователя на вопрос с вариантами', 'verbose_name_plural': 'Ответы пользователей на вопрос с вариантами'},
        ),
        migrations.AlterModelOptions(
            name='userscaleanswer',
            options={'verbose_name': 'Ответ пользователя на вопрос со шкалой', 'verbose_name_plural': 'Ответы пользователей на вопрос со шкалой'},
        ),
        migrations.RemoveField(
            model_name='answerscounting',
            name='answers_count1',
        ),
        migrations.RemoveField(
            model_name='answerscounting',
            name='answers_count2',
        ),
        migrations.RemoveField(
            model_name='answerscounting',
            name='answers_count3',
        ),
        migrations.RemoveField(
            model_name='answerscounting',
            name='answers_count4',
        ),
        migrations.RemoveField(
            model_name='answerscounting',
            name='answers_count5',
        ),
    ]
