# Generated by Django 3.2.5 on 2021-07-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useroptionanswer_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroptionanswer',
            name='date_time_answer',
        ),
        migrations.RemoveField(
            model_name='userscaleanswer',
            name='date_time_answer',
        ),
    ]
