# Generated by Django 3.2.6 on 2021-08-09 15:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_chats_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chats',
            new_name='Chat',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
