# Generated by Django 3.2.7 on 2021-10-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_chat_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datings',
            name='algorithm',
            field=models.CharField(blank=True, choices=[('A1', 'Алгоритм 1'), ('A2', 'Алгоритм 2'), ('A3', 'Алгоритм 3'), ('HBF', 'История по ощущениям'), ('SSA', 'Алгоритм поиска тождеств'), ('ASA', 'Алгоритм поиска противоположности'), ('A4', 'Алгоритм 4')], max_length=120, null=True, verbose_name='Алгоритм'),
        ),
    ]
