# Generated by Django 3.2.4 on 2021-06-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group_question', models.CharField(max_length=200, verbose_name='Название группы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Группа вопросов',
                'verbose_name_plural': 'Группы вопросов',
            },
        ),
        migrations.CreateModel(
            name='QuestionWithScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_number', models.PositiveIntegerField(verbose_name='Номер вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.groupquestion', verbose_name='Группа вопросов')),
            ],
            options={
                'verbose_name': 'Вопрос со шкалой',
                'verbose_name_plural': 'Вопросы со шкалой',
            },
        ),
        migrations.CreateModel(
            name='QuestionWithOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_number', models.PositiveIntegerField(verbose_name='Номер вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.groupquestion', verbose_name='Группа вопросов')),
            ],
            options={
                'verbose_name': 'Вопрос с вариантами',
                'verbose_name_plural': 'Вопросы с вариантами',
            },
        ),
        migrations.CreateModel(
            name='AnswerScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(verbose_name='Номер строки с ответами')),
                ('left_answer_text', models.TextField(verbose_name='Ответ с левой стороны шкалы')),
                ('right_answer_text', models.TextField(verbose_name='Ответ с правой стороны шкалы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionwithscale', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ на вопросы со шкалой',
                'verbose_name_plural': 'Ответы на вопросы со шкалой',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Текст варианта ответа')),
                ('answer_value', models.TextField(verbose_name='Значение варианта ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionwithoption', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ на вопросы с вариантами',
                'verbose_name_plural': 'Ответы на вопросы с вариантами',
            },
        ),
    ]
