# Generated by Django 3.2.5 on 2021-07-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionwithscale',
            name='published_or_not',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
