# Generated by Django 3.2.5 on 2021-07-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionwithscale_published_or_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionwithoption',
            name='published_or_not',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
