# Generated by Django 3.2.5 on 2021-07-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_answeroption_answer_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerscale',
            name='order_number',
        ),
    ]
