# Generated by Django 3.2.5 on 2021-07-16 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_answerscale_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionwithoption',
            name='question_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.groupquestion', verbose_name='Группа вопросов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionwithscale',
            name='question_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.groupquestion', verbose_name='Группа вопросов'),
        ),
    ]
