# Generated by Django 3.2.6 on 2021-08-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210804_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquestion',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
    ]
