# Generated by Django 3.2.6 on 2021-08-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_groupquestion_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquestion',
            name='order',
            field=models.IntegerField(default=0, unique=True, verbose_name='Прядок'),
        ),
    ]
