# Generated by Django 3.2.5 on 2021-07-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210709_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='congratulations_after_test',
            field=models.BooleanField(default=False, verbose_name='Был показан экрана поздравления после прохождения теста'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='test_result_demo',
            field=models.CharField(choices=[('NFNP', 'Не найдены, пользователь не оплатил'), ('NFP', 'Не найдены, пользователь оплатил'), ('FNP', 'Найдены, пользователь не оплатил'), ('FP', 'Найдены, пользователь оплатил')], default='NFNP', max_length=4, verbose_name='Демонстрация результатов прохождения теста'),
        ),
    ]
