# Generated by Django 3.2.6 on 2021-08-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210728_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photoURL',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo', verbose_name='Фото'),
        ),
    ]
