# Generated by Django 3.2.5 on 2021-07-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test_status',
            field=models.CharField(choices=[('start', 'Тестирование не начато'), ('inprogress', 'Тестирование в процессе'), ('finish', 'Тестирование завершено')], default='start', max_length=10, verbose_name='Статус прохождения теста'),
        ),
    ]
