# Generated by Django 3.2.5 on 2021-07-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number_foto_history_by_felling',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер фото истории по ощущениям'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='partner_type',
            field=models.CharField(blank=True, choices=[('GM', 'Для гостевого брака'), ('FAM', 'Для создания семьи'), ('JFF', 'Для просто поболтать и вместе потусить')], max_length=120, null=True, verbose_name='Ищу партнера'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='purpose_meet',
            field=models.CharField(blank=True, choices=[('SAME', 'Такого, как я'), ('ANTI', 'Мою противоположность'), ('MATH', 'Выбор путем математического алгоритма')], max_length=120, null=True, verbose_name='Хочу встретить'),
        ),
    ]
